### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by sfgray26** [thekitbag/my-personal-website#1]
Love it mate - so impressive!

**Comment by sfgray26** [comment]
Also I don't know what rention focus is (on the home page) and figured a potential spelling mistake .... or I'm ignorant and haven't heard of it which is probably more likely!

So impressed with this bro - it's a little annoying how much smarter than me you are but massive respect! 👊🏻

**Comment by thekitbag** [comment]
Good spot, rention is not a word 😂

Meant to say retention obvs. Feel free to put in a PR 😜

**Comment by thekitbag** [comment]
fixed!
